# NumPy N-dimensional Array

    # NumPy N-dimensional Array

NumPy is the ndarray, which is a shorthand name for N-dimensional array. When working with NumPy, data in an ndarray is simply referred to as an array. It is a fixed-sized array in memory that contains data of the same type, such as integers or floating point values.
The data type supported by an array can be accessed via the dtype attribute.
The dimensions of an array can be accessed via the shape attribute.
A simple way to create an array from data or simple Python data structures is to use the array() function.

In [8]:
from numpy import array
l = [[1.0, 3.5, 5.4], [2.0, 5.0, 6.0]]
a = array(l)

In [9]:
print(a)
print(a.shape)
print(a.dtype)

[[1.  3.5 5.4]
 [2.  5.  6. ]]
(2, 3)
float64


In [ ]:
# Functions to Create Arrays

The empty() function will create a new array of the specified shape. The argument to the 
function is an array or tuple that specifies the length of each dimension of the array to 
create. The values or content of the created array will be random.

The zeros() function will create a new array of the specified size with the contents filled 
with zero values. The argument to the function is an array or tuple that specifies the length 
of each dimension of the array to create. 

The ones() function will create a new array of the specified size with the contents filled with
one values. The argument to the function is an array or tuple that specifies the length of each
dimension of the array to create

In [7]:
from numpy import zeros 
from numpy import empty
from numpy import ones
a = empty([3,3])
b = zeros([3,5])
c = ones([5,2])
print(c)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


# Functions to Create Arrays

Vertical Stack
Given two or more existing arrays, you can stack them vertically using the vstack() function.

Horizontal Stack
Given two or more existing arrays, you can stack them horizontally using the hstack() function.

In [9]:
from numpy import array
from numpy import vstack
from numpy import hstack
a1 = array([1,2,3])
a2 = array([4,5,6])
a3 = vstack((a1,a2))
a4 = hstack((a1,a2))
print(a4)
print(a4.shape)

[1 2 3 4 5 6]
(6,)


# Index, Slice and Reshape NumPy Arrays

5.2 From List to Arrays

5.2.1 One-Dimensional List to Array

5.2.2 Two-Dimensional List of Lists to Array


In [2]:
from numpy import array

#################One-Dimensional List to Array#######################
d1 = array([11, 22, 33, 44, 55])
d2 = array([[11, 22],[33, 44],[55, 66]])
#print(type(d2))
#print(d2[0,1])
#print(d1[3:])
#print(d1[0])

#################Two-Dimensional List to Array#######################
data = [[11, 22, 33], 
        [44, 55, 66], 
        [77, 88, 99]]
data = array(data)    
#print(data[0:2,1:3]) #Slicing of matrix data id (From row: to row , from column to column)

data1 = array([[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])
split = 2
train, test = data1[:split,:], data1[split:,:]
#print(train)
#print(d1.shape)

d1 = d1.reshape((d1.shape[0],1))
#print(d1.shape[0])
#print(d1, d1.shape)

data2 = array([[11, 22],[33, 44],[55, 66]])
data2 = data2.reshape((data2.shape[0],data2.shape[1],1))
#print(data2.shape[1])
print(data2.shape, data2)

(3, 2, 1) [[[11]
  [22]]

 [[33]
  [44]]

 [[55]
  [66]]]


In [ ]:
# 6 NumPy Array Broadcasting

Broadcasting  method that uses NumPy and allow array arithmetic between arrays with a difierent
shape or size. Broadcasting solves the problem of arithmetic between arrays of differing shapes 
by in effect replicating the smaller array along the last mismatched dimension.
Numpy makes memory and computationally eficient use of existing structures in memory that in 
effect achieve the same result.

6.4.1 Scalar and One-Dimensional Array
6.4.3 One-Dimensional and Two-Dimensional Arrays

6.5 Limitations of Broadcasting

broadcasting, can only be performed when the shape of each dimension in the arrays are equal 
or one has the dimension size of 1.

In [5]:
# Scalar and One-Dimensional Array
from numpy import array
a = array([1,2,3])
b = 2
#print(a+b)

#One-Dimensional and Two-Dimensional Arrays
A = array([[1, 2, 3],[11, 22, 33]])
b = array([5, 6, 7])
print(A+b)

b1 = array([5, 6, 2, 6])
#print(A+b1) #ValueError: operands could not be broadcast together with shapes (2,3) (2,)

ValueError: operands could not be broadcast together with shapes (2,3) (4,) 