# 18. Predictive Modeling Project Template

18.1.1 Use A Structured Step-By-Step Process

Any predictive modeling machine learning project can be broken down into six common tasks and use as ML project template for any ML problem.

1. Define Problem.
    a} Load Libraries
    b} Load Dataset
    
2. Summarize Data.
    a} Discriptive Statistics
    b} Data Visualization
    
3. Prepare Data.
    a} Data Cleaning 
    b} Feature Selection 
    c} Data Transformation
    
4. Evaluate algorithm
    a} Split out validation dataset
    b} Test options and evaluate metric
    c} Spot check algorithm
    d} Compare algorithm 

5. improve result
    a} Algorithm Tuning 
    b} Ensembles
    
6. present result
    a} Prediction on validation dataset
    b} create standalone model on entire training dataset
    c} save model for later use 
    
This is general structure and to work through predictive modeling ML problem in python, we need to map Python onto this process.


# 19. ML Project in Python Step-By-Step

to see how all of the pieces of a predictive modeling machine learning project actually fit together, will complete the classification of iris flowers project step by step using Python.

In [3]:
#################### 1. Define Problem. ##################################
### a} Load Libraries
from numpy import array
from pandas import read_csv
from pandas.tools.plotting import scatter_matrix
from matplotlib import pyplot
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

###b} Load Dataset
dataset = read_csv('C:/Users/Satish/python_files/Iris.csv')

######################## 2. Summarize Data. ########################################
######## a} Discriptive Statistics
# print(dataset.head(5)) #Peek at the Data
# print(dataset.shape) # Dimensions of Dataset
# print(dataset.describe()) #Statistical Summary
# print(dataset.groupby('Species').size()) # Class Distribution
#### Each class has same no. of instances

######### b} Data Visualization 
##### Univariate Plots
# dataset.plot(kind='box', subplots=True, layout=(2,5), sharex=False, sharey=False) # Boxplot
# dataset.plot(kind='density', subplots=True, layout=(2,5), sharex=False, sharey=False) # Density plot
# dataset.hist()
# pyplot.show()
#### from above plot it looks like two attribute Sepal-length and Sepal-width has Gaussian  
#### Distribution, we can use algo that explot this assumptions

##### Multivariate Plots
# scatter_matrix(dataset)
# pyplot.show()
### The diagonal grouping of some pairs of attributes. This suggests a high correlation and
### a predictable relationship.

############################# 4. Evaluate algorithm ############################
##### 1 Create a Validation Dataset

array = dataset.values
x = array[:,1:5]
# print(x)
y = array[:,5:]
# print(y)
validation_size = 0.2
seed = 17
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=validation_size, random_state = seed)

############# 2 Test Harness

# We will use 10-fold cross validation to estimate accuracy.This will split  dataset into 10
# parts, train on 9 and test on 1 

############ 3 Build Models
#### Spot-Check Algorithms  
models = []
models.append(('LR', LogisticRegression()))
models.append(('DT', DecisionTreeClassifier()))
models.append(('LDA', LinearDiscriminantAnalysis()))
models.append(('KNN', KNeighborsClassifier()))
models.append(('GNB', GaussianNB()))
models.append(('SVM', SVC()))

################### evaluate each model in turn ###################################
results = []
names = []
for name, model in models:
    kfold = KFold(n_splits=10, random_state=seed)
    cv_results = cross_val_score(model, x_train, y_train, cv=kfold, scoring='accuracy')
    results.append(cv_results)
    names.append(name)
    print(name, cv_results.mean(), cv_results.std())
##### We can see that LDA and SVM has largest estimated accuracy score


#### compare algorithm
# fig = pyplot.figure()
# fig.suptitle('Algorithm comparison')
# ax = fig.add_subplot(111)
# pyplot.boxplot(results)
# ax.set_xticklabels(names)
# pyplot.show()

### make prediction on test dataset
lda = LinearDiscriminantAnalysis()
lda.fit(x_train, y_train)
prediction = lda.predict(x_test)

print(accuracy_score(y_test, prediction)) 
### The accuracy is 96.66%

print(confusion_matrix(y_test, prediction))
### Confusion matrix shows only 1 error
# [[ 7  0  0]
#  [ 0 11  0]
#  [ 0  1 11]]


print(classification_report(y_test, prediction))
### the classification report provides a breakdown of each class by precision, recall, f1-score
### and support showing excellent results (provided the validation dataset was small).




C:\Users\Satish\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Satish\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Satish\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Satish\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,

LR 0.95 0.06666666666666667
DT 0.9416666666666667 0.06508541396588878
LDA 0.9833333333333332 0.03333333333333335
KNN 0.95 0.05527707983925667
GNB 0.9583333333333333 0.05590169943749474
SVM 0.975 0.05335936864527373
0.9666666666666667
[[ 7  0  0]
 [ 0 11  0]
 [ 0  1 11]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         7
Iris-versicolor       0.92      1.00      0.96        11
 Iris-virginica       1.00      0.92      0.96        12

    avg / total       0.97      0.97      0.97        30



C:\Users\Satish\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Satish\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
